### ISSUE TITLE
updateEnvironment Task 

### ISSUE THREAD

**Issue by gianarb** [wdalmut/phing-aws#1]
Integration with updateEnvironment API call to deploy new application's version to specific environment

http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.ElasticBeanstalk.ElasticBeanstalkClient.html#_updateEnvironment

@wdalmut is it crazy? :)

**Comment by wdalmut** [comment]
no it is something that i have to add to this project in order to sopport continuous delivery.

;)

**Comment by gianarb** [comment]
In this moment there aren't solution to start a new deploy in this project?
Correct? :)

**Comment by wdalmut** [comment]
we have to add the update env, next week we migrate another project that will use continuous delivery (i don't know if they use phing)  on elastic beanstalk

**Comment by gianarb** [comment]
Ok I try to submit a PR with this feature..
